//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2021.07.09 at 09:23:41 PM IST 
//

package com.oyo.rooms.service;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import jakarta.json.bind.annotation.JsonbDateFormat;

/**
 * <p>
 * Java class for booking-details complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="booking-details"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="booking-no" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="person-name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mobile-no" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="email-address" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="id-type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="id-proof" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="checkin-date" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="checkout-date" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="roomType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="amount-paid" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="balance-amount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "booking-details", propOrder = { "bookingNo", "personName", "mobileNo", "emailAddress", "idType",
		"idProof", "checkinDate", "checkoutDate", "roomType", "amountPaid", "balanceAmount" })
@XmlRootElement(name = "booking-details")
public class BookingDetails {

	@XmlElement(name = "booking-no", required = true)
	protected String bookingNo;
	@XmlElement(name = "person-name", required = true)
	protected String personName;
	@XmlElement(name = "mobile-no", required = true)
	protected String mobileNo;
	@XmlElement(name = "email-address", required = true)
	protected String emailAddress;
	@XmlElement(name = "id-type", required = true)
	protected String idType;
	@XmlElement(name = "id-proof", required = true)
	protected String idProof;
	@XmlElement(name = "checkin-date", required = true)
	@XmlSchemaType(name = "date")
	@JsonbDateFormat(value = "dd/MM/yyyy")
	protected Date checkinDate;
	@XmlElement(name = "checkout-date", required = true)
	@XmlSchemaType(name = "date")
	@JsonbDateFormat(value = "dd/MM/yyyy")
	protected Date checkoutDate;
	@XmlElement(required = true)
	protected String roomType;
	@XmlElement(name = "amount-paid")
	protected float amountPaid;
	@XmlElement(name = "balance-amount")
	protected float balanceAmount;

	/**
	 * Gets the value of the bookingNo property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBookingNo() {
		return bookingNo;
	}

	/**
	 * Sets the value of the bookingNo property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setBookingNo(String value) {
		this.bookingNo = value;
	}

	/**
	 * Gets the value of the personName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPersonName() {
		return personName;
	}

	/**
	 * Sets the value of the personName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setPersonName(String value) {
		this.personName = value;
	}

	/**
	 * Gets the value of the mobileNo property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMobileNo() {
		return mobileNo;
	}

	/**
	 * Sets the value of the mobileNo property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setMobileNo(String value) {
		this.mobileNo = value;
	}

	/**
	 * Gets the value of the emailAddress property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEmailAddress() {
		return emailAddress;
	}

	/**
	 * Sets the value of the emailAddress property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setEmailAddress(String value) {
		this.emailAddress = value;
	}

	/**
	 * Gets the value of the idType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIdType() {
		return idType;
	}

	/**
	 * Sets the value of the idType property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setIdType(String value) {
		this.idType = value;
	}

	/**
	 * Gets the value of the idProof property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIdProof() {
		return idProof;
	}

	/**
	 * Sets the value of the idProof property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setIdProof(String value) {
		this.idProof = value;
	}

	/**
	 * Gets the value of the checkinDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public Date getCheckinDate() {
		return checkinDate;
	}

	/**
	 * Sets the value of the checkinDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setCheckinDate(Date value) {
		this.checkinDate = value;
	}

	/**
	 * Gets the value of the checkoutDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public Date getCheckoutDate() {
		return checkoutDate;
	}

	/**
	 * Sets the value of the checkoutDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setCheckoutDate(Date value) {
		this.checkoutDate = value;
	}

	/**
	 * Gets the value of the roomType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRoomType() {
		return roomType;
	}

	/**
	 * Sets the value of the roomType property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setRoomType(String value) {
		this.roomType = value;
	}

	/**
	 * Gets the value of the amountPaid property.
	 * 
	 */
	public float getAmountPaid() {
		return amountPaid;
	}

	/**
	 * Sets the value of the amountPaid property.
	 * 
	 */
	public void setAmountPaid(float value) {
		this.amountPaid = value;
	}

	/**
	 * Gets the value of the balanceAmount property.
	 * 
	 */
	public float getBalanceAmount() {
		return balanceAmount;
	}

	/**
	 * Sets the value of the balanceAmount property.
	 * 
	 */
	public void setBalanceAmount(float value) {
		this.balanceAmount = value;
	}

}
