//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2021.07.09 at 09:23:41 PM IST 
//


package com.oyo.rooms.service;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.oyo.rooms.service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReservationInfo_QNAME = new QName("http://www.oyo.com/rooms/service", "reservation-info");
    private final static QName _BookingDetails_QNAME = new QName("http://www.oyo.com/rooms/service", "booking-details");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.oyo.rooms.service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReservationInfo }
     * 
     */
    public ReservationInfo createReservationInfo() {
        return new ReservationInfo();
    }

    /**
     * Create an instance of {@link BookingDetails }
     * 
     */
    public BookingDetails createBookingDetails() {
        return new BookingDetails();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReservationInfo }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ReservationInfo }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.oyo.com/rooms/service", name = "reservation-info")
    public JAXBElement<ReservationInfo> createReservationInfo(ReservationInfo value) {
        return new JAXBElement<ReservationInfo>(_ReservationInfo_QNAME, ReservationInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BookingDetails }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BookingDetails }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.oyo.com/rooms/service", name = "booking-details")
    public JAXBElement<BookingDetails> createBookingDetails(BookingDetails value) {
        return new JAXBElement<BookingDetails>(_BookingDetails_QNAME, BookingDetails.class, null, value);
    }

}
